name: Test Terraform

on:
  pull_request:
    branches:
      - "main"

jobs:
  test-terraform:
    name: Test Terraform
    runs-on: ubuntu-latest

    env:
      TF_VERSION: 1.0.0

    steps:
      # 1. Checkout do código-fonte
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.0.0"

      # 3. Verificar formatação do Terraform
      - name: Terraform Format Check
        run: terraform -chdir=src/infrastructure/terraform fmt -check -recursive

      # 4. Inicializar o Terraform
      - name: Terraform Init
        run: terraform -chdir=src/infrastructure/terraform init

      # 5. Validar a configuração do Terraform
      - name: Terraform Validate
        run: terraform -chdir=src/infrastructure/terraform validate

      # 6. Planejar as mudanças de infraestrutura e salvar o plano
      - name: Terraform Plan
        run: terraform -chdir=src/infrastructure/terraform plan -out=tfplan
